mongo:
  #url: mongodb://ezshipptesting:ezshipptesting@betadb.ezshipp.com:1234(betatest)
  uri: mongodb://ezshippDBA:ezshippevontex@db.ezshipp.com:1234/ezshipp
  db: ezshipp
redis:
  host: localhost
  port: 6379
mail:
  protocol: smtp
  host: smtp.gmail.com
  port: 587
  password: ######
  properties.mail.smtp.auth: true
  properties.mail.smtp.starttls.enable: true



