spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://ezshippDBA:ezshippevontex@db.ezshipp.com:1234/ezshipp
      #uri: mongodb://ezshipptesting:ezshipptesting@betadb.ezshipp.com:1234/ezshipp
      db: ezshipp
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: srinivas.seri@ezshipp.com
    password: #######
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
redis:
  host: localhost
  port: 6379
server:
 port: 5000
sparkpost:
  apikey: 907889aed76dde6a1207e1479d387c89b11badb3
  sender: no-reply@ezshipp.com
  url: https://api.sparkpost.com/api/v1/
  recepients: srinivas.seri@ezshipp.com
google:
  apikey: AIzaSyBelEh0cEBYDdkTonoS7bYhyu9RuOEC-kE
logging:
  file: /logs/service.log
reports:
  path: ~/Documents/ezshipp-reports
mailgun:
  apikey: key-0d5ef51597cd2abdcc2687272aeb7a4f
  domainname: www.ezshipp.com
  fromuser: no-reply@ezshipp.com